### ISSUE TITLE
Invalid BlobType Error

### ISSUE THREAD

**Issue by LukeBillo** [jsreport/jsreport-fs-store-azure-storage-persistence#1]
```
2018-05-15T08:01:32.324662598Z 2018-05-15T08:01:32.324Z - [32minfo[39m: fs store is persisting using azure-storage
2018-05-15T08:01:32.450330552Z 2018-05-15T08:01:32.450Z - [32minfo[39m: fs store is synchronizing using azure-sb
2018-05-15T08:01:32.627461250Z 2018-05-15T08:01:32.627Z - [32minfo[39m: fs store is loading data
2018-05-15T08:01:34.373228658Z 2018-05-15T08:01:34.373Z - [31merror[39m: Error occured during reporter init StorageError: The blob type is invalid for this operation.
2018-05-15T08:01:34.373281259Z RequestId:9dc123f8-301e-008c-3522-ec4ee7000000
2018-05-15T08:01:34.373288959Z Time:2018-05-15T08:01:34.3526037Z
2018-05-15T08:01:34.373295859Z     at Function.StorageServiceClient._normalizeError (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1189:23)
2018-05-15T08:01:34.373303059Z     at BlobService.StorageServiceClient._processResponse (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:736:50)
2018-05-15T08:01:34.373310259Z     at Request.processResponseCallback [as _callback] (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)
2018-05-15T08:01:34.373329359Z     at Request.self.callback (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:188:22)
2018-05-15T08:01:34.373336459Z     at emitTwo (events.js:126:13)
2018-05-15T08:01:34.373343359Z     at Request.emit (events.js:214:7)
2018-05-15T08:01:34.373350259Z     at Request.<anonymous> (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:1171:10)
2018-05-15T08:01:34.373357659Z     at emitOne (events.js:116:13)
2018-05-15T08:01:34.373364859Z     at Request.emit (events.js:211:7)
2018-05-15T08:01:34.373371759Z     at IncomingMessage.<anonymous> (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:1091:12)
2018-05-15T08:01:34.373379059Z     at Object.onceWrapper (events.js:313:30)
2018-05-15T08:01:34.373385959Z     at emitNone (events.js:111:20)
2018-05-15T08:01:34.373392759Z     at IncomingMessage.emit (events.js:208:7)
2018-05-15T08:01:34.373399559Z     at endReadableNT (_stream_readable.js:1064:12)
2018-05-15T08:01:34.373406559Z     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-05-15T08:01:34.373422959Z     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I get the following stack trace when spinning up an Azure Web App with Docker containers. 
The following blob storages were generated by JsReport, none existed before:
![](https://i.imgur.com/14unhDw.png)

So to some extent, it has worked - but for some reason fails to initialise the docker containers.

Using the configuration from [this page](https://jsreport.net/learn/fs-store#azure-storage)

**Comment by pofider** [comment]
Thanks. I can replicate it, working on fix...

**Comment by pofider** [comment]
This is now fixed in jsreport-fs-store-azure-storage-persistence@1.0.1.

You can create your own docker image with it or use mine
pofider/jsreport:2.0.1-full

Please just remove file `settings` from azure storage before starting app.
